#!/bin/bash

#read in resources
[[ -f ~/.Xresources  ]] && xrdb -merge -I$HOME ~/.Xresources

# enviorment variables
export BROWSER=firefox &
export EDITOR=vim &
export TERMINAL=roxterm &
export DE=i3 &
export QT_STYLE_OVERRIDE=gtk2

# keyboard and mouse modifications, (swedish keyboard)
# setxkbmap se &
setxkbmap gb &
numlockx &
keynav &
unclutter &

# Visual bling
compton --config ~/.compton.conf --backend glx --vsync opengl-swc --xrender-sync --xrender-sync-fence &

killall xiccd
xiccd & # color correction

#messages
dunst -config .dunst/dunstrc &

#audio
pulseaudio --start &

# applets
nm-applet &
pasystray &

# set wallpaper
./.fehbg
# conky --conf .conkyleft.conkyrc &
# conky --conf .conkyright.conkyrc &

# locker script
xautolock -time 15 -locker ~/Sync/dotfiles/i3lock/lock-trans.sh &

#autostart
#hexchat --minimize=2 &

