#!/bin/bash

# read in resources
[[ -f ~/.Xresources  ]] && xrdb -merge -I$HOME ~/.Xresources

[[ -f ./home/rickisen/.screenlayout/default.sh  ]] && ./home/rickisen/.screenlayout/default.sh

# enviorment variables
export BROWSER=qutebrowser &
export EDITOR=vim &
export TERMINAL=kitty &
export DE=i3 &
export QT_STYLE_OVERRIDE=gtk2 &

# keyboard and mouse modifications, (swedish keyboard)
setxkbmap gb &
numlockx &
keynav &
unclutter &

# Visual bling
compton --config ~/Programming/mine/dotfiles/home/compton.conf &
# killall xiccd
# xiccd & # color correction
# xcalib -gc 0.8 -a -s 0 &

#messages
dunst -config .dunst/dunstrc &

#audio
#$(pulseaudio --kill ; pulseaudio --start) &

# applets
nm-applet &
pasystray &

# set wallpaper
# ./.fehbg &
# conky --conf .conkyleft.conkyrc &
# conky --conf .conkyright.conkyrc &
./bin/random-wallpaper &

# locker script
xautolock -time 15 -locker ~/bin/i3lock/lock-trans.sh &

# gnome keyring
#eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
#export SSH_AUTH_SOCK
#dbus-update-activation-environment --systemd DISPLAY &

#autostart
#hexchat --minimize=2 &
