" ---- pathogen ----------------------------
execute pathogen#infect()
filetype plugin indent on

"-- syntastic -------------------------------
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_html_tidy_exec = 'tidy'
let g:syntastic_cpp_compiler = 'g++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 '

" airline -------------------------------
:set laststatus=2 "allways show airline
let g:airline_powerline_fonts = 1

" colorizer ---------------------------------
let g:colorizer_maxlines = 500 



" frontend/html/css settings ------------------------
autocmd FileType html,css	setlocal expandtab
autocmd Filetype html,css	setlocal shiftwidth=2
autocmd Filetype html,css	setlocal softtabstop=2
"autocmd Filetype html,css	setlocal tabstop=2

au BufNewFile,BufRead *.css    	setl omnifunc=css3#complete

" ------------------------- UI ------------------------------------
" set color 
if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
	set t_Co=256
endif
colorscheme atom-dark-256

syntax on
set number
set relativenumber
set nowrap

" map :wa to keybinding
nmap <c-o> :wa<CR>
imap <c-o> <ESC>:wa<CR>

" CamelCaseMotion
nmap c,w c,e
omap i,w i,e
xmap i,w i,e 

" folding
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

set pastetoggle=<F2>
