set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Keep Plugin commands between vundle#begin/end.

Plugin 'Auto-Pairs'

Plugin 'vim-cpp-enhanced-highlight'

Plugin 'surround.vim'

Plugin 'bling/vim-airline'

Plugin 'Syntastic'

Plugin 'Colorizer--Brabandt'

Plugin 'html_autoclosetag.vim'

Plugin 'closetag.vim'

Plugin 'AutoComplPop'

Plugin 'camelcasemotion'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
syntax on
"set number
set rnu

if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
	set t_Co=256
endif

if has("gui_running")
	set guifont=Source\ Code\ Pro\ for\ Powerline\ 10
	set guioptions-=m  "menu bar
	set guioptions-=T  "toolbar
	set guioptions-=r  "scrollbar
endif

set laststatus=2 

let g:syntastic_cpp_compiler = 'g++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 '

let g:EclimCompletionMethod = 'omnifunc'

" frontend settings
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd Filetype css,html setlocal tabstop=4
au FileType xhtml,xml,html so ~/.vim/bundle/HTML-AutoCloseTag/ftplugin/html_autoclosetag.vim

"camelcasemotion
nmap c,w c,e
omap i,w i,e
xmap i,w i,e 

colorscheme atom-dark-256
