set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Keep Plugin commands between vundle#begin/end. -------------------------

Plugin 'Auto-Pairs'

Plugin 'vim-cpp-enhanced-highlight'

Plugin 'surround.vim'

Plugin 'bling/vim-airline'

Plugin 'Syntastic'

Plugin 'Colorizer--Brabandt'

Plugin 'html_autoclosetag.vim'

Plugin 'AutoComplPop'

Plugin 'camelcasemotion'

Plugin 'MatchTag'

Plugin 'commentary.vim'

Plugin 'css3-syntax-plus'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
" ---------------------------------------------------------------------------------------------

" set color depth
if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
	set t_Co=256
endif

colorscheme atom-dark-256

"ui settings
syntax on
set number
set rnu
set nowrap

" map :wa to keybinding
nmap <c-o> :wa<CR>
imap <c-o> <ESC>:wa<CR>

"camelcasemotion
nmap c,w c,e
omap i,w i,e
xmap i,w i,e 

"cpp stuff
let g:syntastic_cpp_compiler = 'g++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 '
let g:EclimCompletionMethod = 'omnifunc'

" frontend/html/css settings
autocmd FileType html		set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css 		set omnifunc=csscomplete#CompleteCSS
autocmd FileType html,css	set nonumber
autocmd FileType html,css 	set norelativenumber
"autocmd Filetype css,html 	setlocal tabstop=2
"au FileType xhtml,xml,html so ~/.vim/bundle/HTML-AutoCloseTag/ftplugin/html_autoclosetag.vim
