#!/bin/bash

#update path
#export PATH=$(echo "$PATH":/home/rickard/bin) &

#read in resources
[[ -f ~/.Xresources  ]] && xrdb -merge -I$HOME ~/.Xresources

# enviorment variables
export BROWSER=firefox &
export EDITOR=vim &
export TERMINAL=urxvt &
export DE=i3 &

# set up dual monitors
.screenlayout/H*.sh &

# keyboard and mouse modifications, (swedish keyboard)
setxkbmap se &
numlockx &
keynav &
unclutter &

# Visual bling
compton --config ~/.compton.conf --backend glx --vsync opengl -b &
#xcalib .color/Eizo-ferrari.icc &


#audio
pulseaudio --start &

# bar
#xmobar &

# set wallpaper
#feh --bg-tile ~/Pictures/wallpaper/Arch-ricki.png
./.fehbg
conky --conf .conkyleft.conkyrc &
conky --conf .conkyright.conkyrc &

# start wm
exec i3

